/**
 * Player faces — backed by the football-faces dataset.
 * https://github.com/nahweeezy/football-faces
 *
 * The index is generated by `npm run faces:build` and dynamically imported the
 * first time Player Mode is opened, so its ~480 KB stays out of the main
 * bundle. Face cutouts themselves are transparent PNGs pulled lazily from the
 * CDN, keyed by Transfermarkt id.
 */

const FOOT_LABEL = { 1: 'Right', 2: 'Left', 3: 'Both' };

/**
 * Lowercase + strip diacritics, so typing "mbappe" finds "Mbappé" and
 * "haaland" finds "Håland". Football names are full of accents and nobody
 * reaches for the compose key mid-search.
 */
const fold = (s) => s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '');

let _cache = null;    // resolved index
let _inflight = null; // de-dupes concurrent loads

/** Loads (and memoises) the player index. */
export function loadFaces() {
  if (_cache) return Promise.resolve(_cache);
  if (_inflight) return _inflight;
  _inflight = import('./data/faces-index.json')
    .then((mod) => {
      const raw = mod.default || mod;
      const { roles, nations, faceBase, players } = raw;
      _cache = {
        roles,
        nations,
        faceBase,
        generated: raw.generated,
        source: raw.source,
        // Decode once; `key` is the pre-lowered haystack used by search.
        players: players.map(([id, name, fullName, roleIdx, natIdx, dob, height, foot]) => ({
          id,
          name,
          fullName: fullName || name,
          role: roles[roleIdx] || 'CM',
          nation: natIdx >= 0 ? nations[natIdx] : '',
          dob,
          height,
          foot: FOOT_LABEL[foot] || '',
          key: fold(`${name} ${fullName}`),
        })),
      };
      return _cache;
    })
    .catch((err) => {
      _inflight = null;           // let a later attempt retry
      throw err;
    });
  return _inflight;
}

/** Transparent PNG cutout for a player id. */
export const faceUrl = (id) =>
  `https://cdn.jsdelivr.net/gh/nahweeezy/football-faces@main/faces/${id}.png`;

/** Whole years since `dob`, or null when the date is missing/unparseable. */
export function ageFrom(dob) {
  if (!dob) return null;
  const born = new Date(dob);
  if (Number.isNaN(born.getTime())) return null;
  const now = new Date();
  let age = now.getFullYear() - born.getFullYear();
  const m = now.getMonth() - born.getMonth();
  if (m < 0 || (m === 0 && now.getDate() < born.getDate())) age--;
  return age >= 0 && age < 120 ? age : null;
}

/**
 * Filtered player lookup.
 *  role    — board role ('CB', 'LW', …); '' for any
 *  nation  — exact nation string; '' for any
 *  query   — case-insensitive substring of common or full name
 *  exclude — Set of ids already placed on the pitch
 * Name matches rank prefix hits first so typing "mes" surfaces Messi.
 */
export function searchFaces(index, { query = '', role = '', nation = '', exclude, limit = 60 } = {}) {
  if (!index) return [];
  const q = fold(query.trim());
  const out = [];
  for (const p of index.players) {
    if (role && p.role !== role) continue;
    if (nation && p.nation !== nation) continue;
    if (q && !p.key.includes(q)) continue;
    if (exclude && exclude.has(p.id)) continue;
    out.push(p);
  }
  if (q) {
    out.sort((a, b) => {
      const ap = fold(a.name).startsWith(q) ? 0 : 1;
      const bp = fold(b.name).startsWith(q) ? 0 : 1;
      return ap - bp || a.name.localeCompare(b.name);
    });
  }
  return out.slice(0, limit);
}

/** Nations present in the current filter context, for the dropdown. */
export function nationsFor(index, role = '') {
  if (!index) return [];
  const seen = new Set();
  for (const p of index.players) {
    if (role && p.role !== role) continue;
    if (p.nation) seen.add(p.nation);
  }
  return [...seen].sort((a, b) => a.localeCompare(b));
}
